server:
  port: 8080
  address: 0.0.0.0

security:
  enableLogin: false

system:
  enableAnalytics: true

# https://github.com/Stirling-Tools/Stirling-PDF/blob/main/app/core/src/main/java/stirling/software/SPDF/config/EndpointConfiguration.java
endpoints:
  toRemove:
    - pipeline
    - ocr-pdf
  groupsToRemove: []
